### ISSUE TITLE
NS 3.0 upgrade: "ui/core/proxy", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by Yamilquery** [bradmartin/nativescript-gif#13]
When I use my application and use the nativescript-gif module, I get the following error:

```
JS: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: Gif.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:890)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:874)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:866)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6119)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
JS: TypeError: Could not load view for: Gif.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:890)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:874)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:866)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6119)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
JS:     at Object.getViewClass (file:///data/data/com.dtech.levenmas/files/app/tns_modules/nativescript-angular/element-registry.js:29:15)
JS:     at ViewUtil.createView (file:///data/data/com.dtech.levenmas/files/app/tns_modules/nativescript-angular/view-util.js:122:44)
JS:     at EmulatedRenderer.NativeScriptRenderer.createElement (file:///data/data/com.dtech.levenmas/files/app/tns_modules/nativescript-angular/renderer.js:104:30)
JS:     at EmulatedRenderer.createElement (file:///data/data/com.dtech.levenmas/files/app/tns_modules/nativescript-angular/renderer.js:206:51)
JS:     at DebugRenderer2.createElement (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:13139:49)
JS:     at createElement (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:9377:27)
JS:     at createViewNodes (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:11989:44)
JS:     at callViewAction (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:12401:13)
JS:     at execComponentViewsAction (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:12340:13)
JS:     at createViewNodes (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:12058:5)
JS:     at createRootView (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:11
JS: 936:5)
JS:     at callWithDebugContext (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:13067:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:12528:12)
JS:     at ComponentFactory_.create (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:9873:46)
JS:     at ComponentFactoryBoundToModule.create (file:///data/data/com.dtech.levenmas/files/app/tns_modules/@angular/core/bundles/core.umd.js:3454:29)
```

This is my package.json

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.levenmas",
    "tns-ios": {
      "version": "3.0.0-rc.1-2017-3-28-2"
    },
    "tns-android": {
      "version": "3.0.0-rc.1"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-angular": "rc",
    "nativescript-gif": "^1.0.9",
    "nativescript-phone": "^1.3.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "rc",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}
```

I think that your module is probably not compatible with tns-core-modules in its RC version...

**Comment by bradmartin** [comment]
Correct, does not support 3.0 yet. Welcoming PRs to update with 3.0 breaking changes.

**Comment by zbranzov** [comment]
I will create NS 3 migration PR tomorrow ;)

**Comment by dxshindeo** [comment]
Waiting impatiently, currently this is the only thing which keeps me from going live with 3.0.0 NS

**Comment by zbranzov** [comment]
It is already opened. Waiting for review.

**Comment by bradmartin** [comment]
2.0.0 published https://www.npmjs.com/package/nativescript-gif
