### ISSUE TITLE
TypeError: Cannot read property 'setImageDrawable' of null

### ISSUE THREAD

**Issue by csimpi** [bradmartin/nativescript-gif#55]
This error message started appearing for no reason. There's no GIF used in the component at all, it's very unreasonable. 

```
JS: TypeError: Cannot read property 'setImageDrawable' of null
JS:     at file: src/webpack:/app/node_modules/nativescript-gif/gif.android.js:96:0
JS:     at ZoneDelegate.invoke (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:372:0)
JS:     at Object.onInvoke (file: src/webpack:/app/node_modules/@angular/core/fesm2015/core.js:28672:0)
JS:     at ZoneDelegate.invoke (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:371:0)
JS:     at Zone.run (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:134:0)
JS:     at file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:1276:0
JS:     at ZoneDelegate.invokeTask (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:406:0)
JS:     at Object.onInvokeTask (file: src/webpack:/app/node_modules/@angular/core/fesm2015/core.js:28659:0)
JS:     at ZoneDelegate.invokeTask (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:405:0)

```

**Comment by shiv19** [comment]
@csimpi It would be helpful if you can tell us the steps to re-create this issue :)
